- pipeline: python_application
  name: Python application
  actions:
  - action: npm run build
    type: BUILD
    docker_image_name: library/node
    docker_image_tag: 22
    execute_commands:
    - "# yarn install"
    - npm install
    - npm run build
    shell: BASH
